on:
  push:
  pull_request:
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX64
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          unityVersion: 2022.3.9f1
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v3
        with:
          name: gameclient-${{ matrix.targetPlatform }}-${{ github.sha }}
          path: bin

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: game-ci/unity-test-runner@v2
        with:
          projectPath: .
          unityVersion: 2022.3.9f1

      - uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: artifacts/test-results.xml
